### ISSUE TITLE
Bramble fails to read scheme

### ISSUE THREAD

**Issue by codedge** [movio/bramble#200]
Bramble does not start and fails with this error message `error decoding response: invalid character 'y' in literal true (expecting 'r'` while reading the following scheme.
I have this schema returned from my service either as `text/plain` or as `application/graphql` content type, but neither works.

**Scheme**

```
type Query {
  node(id: ID!): Node
  aggregate(id: ID!): Aggregate
}

"A node, according to the Relay specification."
interface Node {
  "The id of this node."
  id: ID!
}

type Aggregate implements Node {
  id: ID!
  _id: String!
  totalAmount: Int
  status: String!
}

type Mutation {
  "Creates a Aggregate."
  createAggregate(input: createAggregateInput!): createAggregatePayload
}

"Creates a Aggregate."
input createAggregateInput {
  totalAmount: Int
  status: String!
  clientMutationId: String
}

"Creates a Aggregate."
type createAggregatePayload {
  aggregate: Aggregate
  clientMutationId: String
}
```

<img width="1501" alt="2023-03-13_22 35 18" src="https://user-images.githubusercontent.com/4409904/224837585-50d3d548-e129-4e69-b803-4fac0354db16.png">

I am running bramble via Docker Compose like this:

**docker-compose.yml**

```yaml
version: '3.9'

services:
    # other...

    graphql-gateway:
        build: https://github.com/movio/bramble.git#main
        image: graphql-gateway
        environment:
            - BRAMBLE_SERVICE_LIST=http://php:80/api/graphql/schema
```

Isn't my scheme valid or can somebody spot an issue?
